# Generated by Django 4.2.3 on 2023-08-08 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_remove_chapter_created_at_alter_story_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='chapter',
        ),
        migrations.AddField(
            model_name='chapter',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='story.story'),
        ),
    ]
