# Generated by Django 4.2.3 on 2023-08-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_remove_story_chapter_chapter_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.CharField(default=None),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=models.TextField(),
        ),
    ]
