# Generated by Django 4.2.3 on 2023-08-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_tag_story_category_alter_chapter_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.CharField(default='fiction'),
        ),
    ]
