# Generated by Django 4.2.3 on 2023-08-09 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_remove_story_category_story_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='tag',
        ),
    ]
