# Generated by Django 4.2.3 on 2023-08-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_remove_story_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='tag',
            field=models.CharField(default='Fiction'),
        ),
    ]
