# Generated by Django 4.2.3 on 2023-08-09 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_story_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='story.tag'),
        ),
    ]
