# Generated by Django 4.2.3 on 2023-08-09 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0012_alter_tag_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
    ]
