# Generated by Django 4.2.3 on 2023-08-10 02:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0013_remove_tag_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
