# Generated by Django 4.2.3 on 2023-08-14 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0015_story_likes_alter_story_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='created_at',
        ),
    ]
