# Generated by Django 4.2.3 on 2023-08-15 07:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0020_alter_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='swu_story', to=settings.AUTH_USER_MODEL),
        ),
    ]
