# Generated by Django 4.2.3 on 2023-08-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0021_alter_story_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='story_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
