# Generated by Django 4.2.3 on 2023-08-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0022_chapter_story_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='story_image',
        ),
        migrations.AddField(
            model_name='story',
            name='story_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
